name: validation
on:
  pull_request: 
    branches: [main]
  workflow_dispatch:

jobs:
  pre-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install xmlschema
      - name: Schema validation
        id: schema-validate
        shell: python
        run: |
            import xmlschema
            schema = xmlschema.XMLSchema('MeasurandTaxonomyCatalog.xsd')
      - name: XML validation
        id: xml-validation
        shell: python
        run: |
            import xmlschema
            schema = xmlschema.XMLSchema('MeasurandTaxonomyCatalog.xsd')
            schema.validate('MeasurandTaxonomyCatalog.xml')
  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install xmlschema
            pip install yq
      - name: Get changed catalog
        id: changed-catalog-file
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            MeasurandTaxonomyCatalog.xml
      
      - name: Validate catalog if changed
        id: validate-catalog
        if: steps.changed-catalog-file.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.change-catalog-file.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          python scripts/validator.py -f MeasurandTaxonomyCatalog.xml -d ./

      - name: Get all changed source xml
        id: changed-source-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            source/**.xml
      
      - name: Check if source and catalog changed
        id: changed-source-catalog
        if: steps.changed-source-files.outputs.any_changed == 'true' && steps.changed-catalog-file.outputs.any_changed == 'true'
        run:
          exit 1

      - name: Validate source if changed
        id: valid-changed-source-files
        if: steps.changed-source-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-source-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            echo "$file" >> changed_files.txt
          done
          python scripts/validator.py -l changed_files.txt -d ./
      
      - name: Merge source files
        id: merge-source-files
        if: steps.changed-source-files.outputs.any_changed == 'true' && steps.valid-changed-source-files.outcome == 'success'
        run: |
          sh scripts/combiner.sh ./source
          python scripts/validator.py -f merge.xml -d ./source
              
